---
title: "Practice Activity: Layering in ggplot"
format: html
editor: visual
embed-resources: true
---

## Original Plot

```{r libraries}
library(dslabs)
library(tidyverse)
library(dplyr)
```

```{r data}

data(us_contagious_diseases)
the_disease <- "Measles"
dat <- us_contagious_diseases %>%
  filter(!state%in%c("Hawaii","Alaska") & disease == the_disease) %>%
  mutate(rate = count / population * 10000 * 52 / weeks_reporting) 

jet.colors <- colorRampPalette(c("#F0FFFF", "cyan", "#007FFF", "yellow", "#FFBF00", "orange", "red", "#7F0000"), bias = 2.25)

dat %>% mutate(state = reorder(state, desc(state))) %>%
  ggplot(aes(year, state, fill = rate)) +
  geom_tile(color = "white", size = 0.35) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_gradientn(colors = jet.colors(16), na.value = 'white') +
  geom_vline(xintercept = 1963, col = "black") +
  theme_minimal() + 
  theme(panel.grid = element_blank()) +
        coord_cartesian(clip = 'off') +
        ggtitle(the_disease) +
        ylab("") +
        xlab("") +  
        theme(legend.position = "bottom", text = element_text(size = 8)) + 
        annotate(geom = "text", x = 1963, y = 50.5, label = "Vaccine introduced", size = 3, hjust = -0.04)
```

## Updated Plot

```{r updatd}

jet.colors <- colorRampPalette(c("#dae7ed", "cyan", "#007FFF", "yellow", "#FFBF00", "orange", "red", "#7F0000"), bias = 2.25)

dat %>%
  mutate(state = reorder(state, desc(state))) %>%
  ggplot(aes(year, state, fill = rate)) +
  geom_tile(color = "lightgray", size = 0.35) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_fill_gradientn(colors = jet.colors(16), na.value = "#f5fafc") +
  geom_vline(xintercept = 1963, color = "black", linewidth = 0.5) +
  annotate(
    geom = "text",x = 1963, y = 51,
    label = "1963: Measles Vaccine Introduced", hjust = -0.05, size = 4, family = "serif", color = "black"
  ) +
  labs(
    title = "Measles Prevalence in U.S. States (1928–2011)", fill = "Rate per 10,000"
  ) + theme_minimal(base_family = "serif") +
  theme(
    panel.grid = element_blank(), axis.title = element_blank(), legend.position = "bottom", plot.title = element_text(size = 14, face = "bold", color = "black"), 
    panel.background = element_rect(fill = "lightgray", color = "lightgray"),
    plot.background = element_rect(fill = "lightgray", color = "lightgray")
  ) 
# Backgraound color code: https://www.sthda.com/english/wiki/ggplot2-themes-and-background-colors-the-3-elements

```
